run:
  concurrency: 8

linters-settings:
  errcheck:
    check-type-assertions: true
  errorlint:
    asserts: false
    comparison: false
  gocognit:
    min-complexity: 15
  gocritic:
    enabled-checks:
    - appendCombine
    - boolExprSimplify
    - commentedOutCode
    - dupImport
    - emptyFallthrough
    - emptyStringTest
    - equalFold
    - evalOrder
    - hexLiteral
    - indexAlloc
    - initClause
    - methodExprCall
    - nestingReduce
    - nilValReturn
    - ptrToRefParam
    - rangeExprCopy
    - regexpPattern
    - sloppyReassign
    - stringXbytes
    - truncateCmp
    - typeAssertChain
    - typeUnparen
    - unnecessaryBlock
    - weakCond
    - yodaStyleExpr
  gocyclo:
    min-complexity: 10
  revive:
    rules:
      - name: unused-parameter
        disabled: true

linters:
  disable-all: true
  enable:
  - bodyclose
  - dogsled
  - errcheck
  - errorlint
  - gocognit
  - goconst
  - gocritic
  - goimports
  - goprintffuncname
  - gosimple
  - govet
  - ineffassign
  - misspell
  - nakedret
  - nestif
  - revive
  - staticcheck
  - typecheck
  - unconvert
  - unparam
  - whitespace
  fast: false

issues:
  exclude-files:
  - mock_*.go
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
  - path: helpers/shell_escape.go
    linters:
    - gocyclo
  - path: executors/kubernetes/kubernetes_test.go
    linters:
    - gocyclo
  - path: executors/kubernetes/util_test.go
    linters:
    - gocyclo
  - path: executors/kubernetes/exec_test.go
    linters:
    - gocyclo
  - path: executors/parallels/
    linters:
    - gocyclo
  - path: executors/virtualbox/
    linters:
    - gocyclo
  - linters:
    - revive
    text: "don't use ALL_CAPS in Go names; use CamelCase"
  - linters:
    - revive
    text: "don't use an underscore in package name"
  - path: ".*_test.go"
    linters:
    - bodyclose
    - gocognit
    - goconst
  - path: ".*_test.go"
    text: "Error return value is not checked"
    linters:
    - errcheck
  - path: ".*_test.go"
    text: "regexpMust"
    linters:
    - errcheck
    - gocritic
  - path: ".*_test.go"
    text: "typeUnparen"
    linters:
    - gocritic
  - path: executors/docker/docker_command_test.go # Ignore until https://gitlab.com/gitlab-org/gitlab-runner/-/issues/25385 is solved
    linters:
    - unused
