all: true
dir: '{{.InterfaceDir}}'
filename: 'mocks.go'
structname: "{{.Mock}}{{.InterfaceName | firstUpper}}"
pkgname: '{{.SrcPackageName}}'
template: testify
template-data:
  unroll-variadic: true
packages:
  gitlab.com/gitlab-org/gitlab-runner:
    config:
      exclude-subpkg-regex:
        - executors/internal/autoscaler
      recursive: true
