// Code generated by mockery v2.14.0. DO NOT EDIT.

package secret_engines

import (
	mock "github.com/stretchr/testify/mock"
	vault "gitlab.com/gitlab-org/gitlab-runner/helpers/vault"
)

// MockFactory is an autogenerated mock type for the Factory type
type MockFactory struct {
	mock.Mock
}

// Execute provides a mock function with given fields: client, path
func (_m *MockFactory) Execute(client vault.Client, path string) vault.SecretEngine {
	ret := _m.Called(client, path)

	var r0 vault.SecretEngine
	if rf, ok := ret.Get(0).(func(vault.Client, string) vault.SecretEngine); ok {
		r0 = rf(client, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(vault.SecretEngine)
		}
	}

	return r0
}

type mockConstructorTestingTNewMockFactory interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockFactory creates a new instance of MockFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockFactory(t mockConstructorTestingTNewMockFactory) *MockFactory {
	mock := &MockFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
