// Code generated by mockery v1.1.0. DO NOT EDIT.

package kubernetes

import mock "github.com/stretchr/testify/mock"

// mockLogger is an autogenerated mock type for the logger type
type mockLogger struct {
	mock.Mock
}

// Debugln provides a mock function with given fields: args
func (_m *mockLogger) Debugln(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Warningln provides a mock function with given fields: args
func (_m *mockLogger) Warningln(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}
