// Code generated by mockery v2.53.3. DO NOT EDIT.

package store

import (
	io "io"

	common "gitlab.com/gitlab-org/gitlab-runner/common"

	mock "github.com/stretchr/testify/mock"
)

// mockJobDecoder is an autogenerated mock type for the jobDecoder type
type mockJobDecoder struct {
	mock.Mock
}

type mockJobDecoder_Expecter struct {
	mock *mock.Mock
}

func (_m *mockJobDecoder) EXPECT() *mockJobDecoder_Expecter {
	return &mockJobDecoder_Expecter{mock: &_m.Mock}
}

// Decode provides a mock function with given fields: _a0, _a1
func (_m *mockJobDecoder) Decode(_a0 io.Reader, _a1 *common.Job) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Decode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(io.Reader, *common.Job) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockJobDecoder_Decode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decode'
type mockJobDecoder_Decode_Call struct {
	*mock.Call
}

// Decode is a helper method to define mock.On call
//   - _a0 io.Reader
//   - _a1 *common.Job
func (_e *mockJobDecoder_Expecter) Decode(_a0 interface{}, _a1 interface{}) *mockJobDecoder_Decode_Call {
	return &mockJobDecoder_Decode_Call{Call: _e.mock.On("Decode", _a0, _a1)}
}

func (_c *mockJobDecoder_Decode_Call) Run(run func(_a0 io.Reader, _a1 *common.Job)) *mockJobDecoder_Decode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.Reader), args[1].(*common.Job))
	})
	return _c
}

func (_c *mockJobDecoder_Decode_Call) Return(_a0 error) *mockJobDecoder_Decode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockJobDecoder_Decode_Call) RunAndReturn(run func(io.Reader, *common.Job) error) *mockJobDecoder_Decode_Call {
	_c.Call.Return(run)
	return _c
}

// newMockJobDecoder creates a new instance of mockJobDecoder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockJobDecoder(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockJobDecoder {
	mock := &mockJobDecoder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
