---
name: gitlab_base.CIConfigFile
description: |
  Checks that the `.gitlab-ci.yml` file is referenced properly.
extends: existence
message: "Change the file name to be exactly '.gitlab-ci.yml'."
link: https://docs.gitlab.com/development/documentation/styleguide/availability_details/
vocab: false
level: error
scope: raw
raw:
  - '(?!`\.gitlab-ci\.yml`)`.?gitlab.?ci.?ya?ml`'
