FROM mcr.microsoft.com/powershell

COPY powershell-entrypoint/entrypoint.pre-post-trap.ps1 /entrypoint.ps1

# non-root user required to enable the docker executor's file ownership change
USER 1000:1000

ENTRYPOINT [ "pwsh", "/entrypoint.ps1" ]
