// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package s3

import (
	"context"
	"net/http"
	"net/url"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// newMockMinioClient creates a new instance of mockMinioClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockMinioClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockMinioClient {
	mock := &mockMinioClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockMinioClient is an autogenerated mock type for the minioClient type
type mockMinioClient struct {
	mock.Mock
}

type mockMinioClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockMinioClient) EXPECT() *mockMinioClient_Expecter {
	return &mockMinioClient_Expecter{mock: &_m.Mock}
}

// PresignHeader provides a mock function for the type mockMinioClient
func (_mock *mockMinioClient) PresignHeader(ctx context.Context, method string, bucketName string, objectName string, expires time.Duration, reqParams url.Values, extraHeaders http.Header) (*url.URL, error) {
	ret := _mock.Called(ctx, method, bucketName, objectName, expires, reqParams, extraHeaders)

	if len(ret) == 0 {
		panic("no return value specified for PresignHeader")
	}

	var r0 *url.URL
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, time.Duration, url.Values, http.Header) (*url.URL, error)); ok {
		return returnFunc(ctx, method, bucketName, objectName, expires, reqParams, extraHeaders)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, time.Duration, url.Values, http.Header) *url.URL); ok {
		r0 = returnFunc(ctx, method, bucketName, objectName, expires, reqParams, extraHeaders)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*url.URL)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, time.Duration, url.Values, http.Header) error); ok {
		r1 = returnFunc(ctx, method, bucketName, objectName, expires, reqParams, extraHeaders)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockMinioClient_PresignHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignHeader'
type mockMinioClient_PresignHeader_Call struct {
	*mock.Call
}

// PresignHeader is a helper method to define mock.On call
//   - ctx context.Context
//   - method string
//   - bucketName string
//   - objectName string
//   - expires time.Duration
//   - reqParams url.Values
//   - extraHeaders http.Header
func (_e *mockMinioClient_Expecter) PresignHeader(ctx interface{}, method interface{}, bucketName interface{}, objectName interface{}, expires interface{}, reqParams interface{}, extraHeaders interface{}) *mockMinioClient_PresignHeader_Call {
	return &mockMinioClient_PresignHeader_Call{Call: _e.mock.On("PresignHeader", ctx, method, bucketName, objectName, expires, reqParams, extraHeaders)}
}

func (_c *mockMinioClient_PresignHeader_Call) Run(run func(ctx context.Context, method string, bucketName string, objectName string, expires time.Duration, reqParams url.Values, extraHeaders http.Header)) *mockMinioClient_PresignHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 time.Duration
		if args[4] != nil {
			arg4 = args[4].(time.Duration)
		}
		var arg5 url.Values
		if args[5] != nil {
			arg5 = args[5].(url.Values)
		}
		var arg6 http.Header
		if args[6] != nil {
			arg6 = args[6].(http.Header)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *mockMinioClient_PresignHeader_Call) Return(uRL *url.URL, err error) *mockMinioClient_PresignHeader_Call {
	_c.Call.Return(uRL, err)
	return _c
}

func (_c *mockMinioClient_PresignHeader_Call) RunAndReturn(run func(ctx context.Context, method string, bucketName string, objectName string, expires time.Duration, reqParams url.Values, extraHeaders http.Header) (*url.URL, error)) *mockMinioClient_PresignHeader_Call {
	_c.Call.Return(run)
	return _c
}
