// Code generated by mockery v1.1.0. DO NOT EDIT.

package service_helpers

import (
	service "github.com/kardianos/service"
	mock "github.com/stretchr/testify/mock"
)

// mockStopStarter is an autogenerated mock type for the stopStarter type
type mockStopStarter struct {
	mock.Mock
}

// Start provides a mock function with given fields: _a0
func (_m *mockStopStarter) Start(_a0 service.Service) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(service.Service) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stop provides a mock function with given fields: _a0
func (_m *mockStopStarter) Stop(_a0 service.Service) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(service.Service) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
