// Code generated by mockery v2.14.0. DO NOT EDIT.

package common

import mock "github.com/stretchr/testify/mock"

// mockMasker is an autogenerated mock type for the masker type
type mockMasker struct {
	mock.Mock
}

// SetMasked provides a mock function with given fields: _a0
func (_m *mockMasker) SetMasked(_a0 []string) {
	_m.Called(_a0)
}

type mockConstructorTestingTnewMockMasker interface {
	mock.TestingT
	Cleanup(func())
}

// newMockMasker creates a new instance of mockMasker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockMasker(t mockConstructorTestingTnewMockMasker) *mockMasker {
	mock := &mockMasker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
