// Code generated by mockery v2.43.0. DO NOT EDIT.

package common

import mock "github.com/stretchr/testify/mock"

// MockConfigSaver is an autogenerated mock type for the ConfigSaver type
type MockConfigSaver struct {
	mock.Mock
}

// Save provides a mock function with given fields: filePath, data
func (_m *MockConfigSaver) Save(filePath string, data []byte) error {
	ret := _m.Called(filePath, data)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = rf(filePath, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockConfigSaver creates a new instance of MockConfigSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigSaver {
	mock := &MockConfigSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
