// Code generated by mockery v2.14.0. DO NOT EDIT.

package common

import mock "github.com/stretchr/testify/mock"

// MockSecretResolverRegistry is an autogenerated mock type for the SecretResolverRegistry type
type MockSecretResolverRegistry struct {
	mock.Mock
}

// GetFor provides a mock function with given fields: secret
func (_m *MockSecretResolverRegistry) GetFor(secret Secret) (SecretResolver, error) {
	ret := _m.Called(secret)

	var r0 SecretResolver
	if rf, ok := ret.Get(0).(func(Secret) SecretResolver); ok {
		r0 = rf(secret)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(SecretResolver)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(Secret) error); ok {
		r1 = rf(secret)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: f
func (_m *MockSecretResolverRegistry) Register(f secretResolverFactory) {
	_m.Called(f)
}

type mockConstructorTestingTNewMockSecretResolverRegistry interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockSecretResolverRegistry creates a new instance of MockSecretResolverRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockSecretResolverRegistry(t mockConstructorTestingTNewMockSecretResolverRegistry) *MockSecretResolverRegistry {
	mock := &MockSecretResolverRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
