#!/usr/bin/env bash

distFlavor=${DIST_FLAVOR:-""}

packageCloudURL=${1}
packageCloudRepo=${2}
packageType=${3}
branch=$(echo "${4}" | cut -f 1 -d ' ')
shift 4

push_packagecloud() {
  local dist="${1}"

  echo "===================="
  echo "${dist}"
  echo "===================="

  package_cloud push --verbose --url "${packageCloudURL}" "${packageCloudRepo}/${dist}" out/${packageType}/*.${packageType}
}

releases=$(go run ./scripts/packagecloud-releases.go "$packageType" "$branch")

echo "$packageType distros to package: $releases"

# shellcheck disable=SC2068
for dist in ${releases}
do
    if [[ -z "${distFlavor}" ]] || [[ "${dist}" =~ ${distFlavor} ]]; then
        push_packagecloud "${dist}"
    fi
done
