#!/bin/bash

set -eo pipefail

target=$(echo ${1} | cut -f 1 -d ' ')
case "${target}" in
    bleeding)
        make packagecloud PACKAGE_CLOUD="runner/unstable" \
                          DEB_PLATFORMS="debian/jessie ubuntu/trusty ubuntu/xenial" \
                          RPM_PLATFORMS="el/7 fedora/23"
        ;;
    stable)
        make packagecloud
        ;;
    *)
        echo "Unkown packagecloud upload target: '${target}'"
        exit 1
        ;;
esac
