#!/usr/bin/env bash

set -eo pipefail

target=$(echo ${1} | cut -f 1 -d ' ')
case "${target}" in
    bleeding)
        make packagecloud PACKAGE_CLOUD="runner/unstable" \
                          DEB_PLATFORMS="debian/jessie debian/stretch ubuntu/trusty ubuntu/xenial ubuntu/artful" \
                          RPM_PLATFORMS="el/7 fedora/25"
        ;;
    stable)
        make packagecloud
        ;;
    *)
        echo "Unkown packagecloud upload target: '${target}'"
        exit 1
        ;;
esac
