#!/bin/bash

set -eo pipefail

version=$(cat VERSION || echo dev | sed -e 's/^v//g')
exact_tag=$(git describe --exact-match 2>/dev/null | sed -e 's/^v//g' || echo "")

last_tag=$(git describe --tags --abbrev=0 --match 'v[0-9].[0-9].[0-9]')
commits=$(git log --oneline ${last_tag}..HEAD | wc -l)
revision=$(git rev-parse --short HEAD || echo unknown)

if [[ $(echo ${exact_tag} | grep -E "^[0-9]+\.[0-9]+\.[0-9]+$") ]]; then
    echo $exact_tag
    exit 0
fi

if [[ $(echo ${exact_tag} | grep -E "^[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+$") ]]; then
    echo $exact_tag
    exit 0
fi

echo "${version}~beta.${commits}.g${revision}"
