// Code generated by mockery v1.1.0. DO NOT EDIT.

package gcs

import mock "github.com/stretchr/testify/mock"

// MockMetadataClient is an autogenerated mock type for the MetadataClient type
type MockMetadataClient struct {
	mock.Mock
}

// Email provides a mock function with given fields: serviceAccount
func (_m *MockMetadataClient) Email(serviceAccount string) (string, error) {
	ret := _m.Called(serviceAccount)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(serviceAccount)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(serviceAccount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
