// Code generated by mockery v2.53.3. DO NOT EDIT.

package docker

import (
	container "github.com/docker/docker/api/types/container"
	mock "github.com/stretchr/testify/mock"

	network "github.com/docker/docker/api/types/network"

	types "github.com/docker/docker/api/types"
)

// mockContainerConfigurator is an autogenerated mock type for the containerConfigurator type
type mockContainerConfigurator struct {
	mock.Mock
}

type mockContainerConfigurator_Expecter struct {
	mock *mock.Mock
}

func (_m *mockContainerConfigurator) EXPECT() *mockContainerConfigurator_Expecter {
	return &mockContainerConfigurator_Expecter{mock: &_m.Mock}
}

// ContainerConfig provides a mock function with given fields: image
func (_m *mockContainerConfigurator) ContainerConfig(image *types.ImageInspect) (*container.Config, error) {
	ret := _m.Called(image)

	if len(ret) == 0 {
		panic("no return value specified for ContainerConfig")
	}

	var r0 *container.Config
	var r1 error
	if rf, ok := ret.Get(0).(func(*types.ImageInspect) (*container.Config, error)); ok {
		return rf(image)
	}
	if rf, ok := ret.Get(0).(func(*types.ImageInspect) *container.Config); ok {
		r0 = rf(image)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*container.Config)
		}
	}

	if rf, ok := ret.Get(1).(func(*types.ImageInspect) error); ok {
		r1 = rf(image)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockContainerConfigurator_ContainerConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerConfig'
type mockContainerConfigurator_ContainerConfig_Call struct {
	*mock.Call
}

// ContainerConfig is a helper method to define mock.On call
//   - image *types.ImageInspect
func (_e *mockContainerConfigurator_Expecter) ContainerConfig(image interface{}) *mockContainerConfigurator_ContainerConfig_Call {
	return &mockContainerConfigurator_ContainerConfig_Call{Call: _e.mock.On("ContainerConfig", image)}
}

func (_c *mockContainerConfigurator_ContainerConfig_Call) Run(run func(image *types.ImageInspect)) *mockContainerConfigurator_ContainerConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*types.ImageInspect))
	})
	return _c
}

func (_c *mockContainerConfigurator_ContainerConfig_Call) Return(_a0 *container.Config, _a1 error) *mockContainerConfigurator_ContainerConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockContainerConfigurator_ContainerConfig_Call) RunAndReturn(run func(*types.ImageInspect) (*container.Config, error)) *mockContainerConfigurator_ContainerConfig_Call {
	_c.Call.Return(run)
	return _c
}

// HostConfig provides a mock function with no fields
func (_m *mockContainerConfigurator) HostConfig() (*container.HostConfig, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HostConfig")
	}

	var r0 *container.HostConfig
	var r1 error
	if rf, ok := ret.Get(0).(func() (*container.HostConfig, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *container.HostConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*container.HostConfig)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockContainerConfigurator_HostConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HostConfig'
type mockContainerConfigurator_HostConfig_Call struct {
	*mock.Call
}

// HostConfig is a helper method to define mock.On call
func (_e *mockContainerConfigurator_Expecter) HostConfig() *mockContainerConfigurator_HostConfig_Call {
	return &mockContainerConfigurator_HostConfig_Call{Call: _e.mock.On("HostConfig")}
}

func (_c *mockContainerConfigurator_HostConfig_Call) Run(run func()) *mockContainerConfigurator_HostConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockContainerConfigurator_HostConfig_Call) Return(_a0 *container.HostConfig, _a1 error) *mockContainerConfigurator_HostConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockContainerConfigurator_HostConfig_Call) RunAndReturn(run func() (*container.HostConfig, error)) *mockContainerConfigurator_HostConfig_Call {
	_c.Call.Return(run)
	return _c
}

// NetworkConfig provides a mock function with given fields: aliases
func (_m *mockContainerConfigurator) NetworkConfig(aliases []string) *network.NetworkingConfig {
	ret := _m.Called(aliases)

	if len(ret) == 0 {
		panic("no return value specified for NetworkConfig")
	}

	var r0 *network.NetworkingConfig
	if rf, ok := ret.Get(0).(func([]string) *network.NetworkingConfig); ok {
		r0 = rf(aliases)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*network.NetworkingConfig)
		}
	}

	return r0
}

// mockContainerConfigurator_NetworkConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NetworkConfig'
type mockContainerConfigurator_NetworkConfig_Call struct {
	*mock.Call
}

// NetworkConfig is a helper method to define mock.On call
//   - aliases []string
func (_e *mockContainerConfigurator_Expecter) NetworkConfig(aliases interface{}) *mockContainerConfigurator_NetworkConfig_Call {
	return &mockContainerConfigurator_NetworkConfig_Call{Call: _e.mock.On("NetworkConfig", aliases)}
}

func (_c *mockContainerConfigurator_NetworkConfig_Call) Run(run func(aliases []string)) *mockContainerConfigurator_NetworkConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *mockContainerConfigurator_NetworkConfig_Call) Return(_a0 *network.NetworkingConfig) *mockContainerConfigurator_NetworkConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockContainerConfigurator_NetworkConfig_Call) RunAndReturn(run func([]string) *network.NetworkingConfig) *mockContainerConfigurator_NetworkConfig_Call {
	_c.Call.Return(run)
	return _c
}

// newMockContainerConfigurator creates a new instance of mockContainerConfigurator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockContainerConfigurator(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockContainerConfigurator {
	mock := &mockContainerConfigurator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
