# This job should only run if the UBI images downstream pipeline is successful.
# It does not depend on it since the pipeline incorrectly assumes that it has passed
# when the trigger job is just created. Instead it depends on the whole postreleases stage.
trigger deploy to kubernetes:
  stage: deploy
  variables:
    UPSTREAM_CI_COMMIT_REF: $CI_COMMIT_BRANCH
    UPSTREAM_CI_COMMIT_SHORT_SHA: $CI_COMMIT_SHORT_SHA
  rules:
    # Override rules in .trigger-downstream-pipeline-ref to remove MR pipelines
    - if: '$CI_PROJECT_NAMESPACE !~ /^gitlab-org($|\/)/'
      when: never
    - if: $CI_PROJECT_PATH != "gitlab-org/gitlab-runner"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    # The KUBERNETES_DEPLOY_BRANCH variable would usually be "main"
    # but in some cases we might want to deploy from a different branch
    # For example, a feature branch.
    - if: $CI_COMMIT_BRANCH == $KUBERNETES_DEPLOY_BRANCH || ($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $KUBERNETES_DEPLOY_BRANCH == "")
      changes: !reference [.code-backstage-patterns]
      variables:
        UPSTREAM_CI_COMMIT_REF: $CI_COMMIT_REF_NAME
    - if: $CI_COMMIT_REF_NAME =~ /\Av[0-9]+\.[0-9]+\.[0-9]+?\z/
      changes: !reference [.code-backstage-patterns]
      variables:
        UPSTREAM_CI_COMMIT_REF: $CI_COMMIT_REF_NAME
    - if: $CI_COMMIT_REF_NAME =~ /\Av[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]+)?\z/
      changes: !reference [.code-backstage-patterns]
      variables:
        UPSTREAM_CI_COMMIT_REF: $CI_COMMIT_REF_NAME
  trigger:
    project: gitlab-org/ci-cd/runner-tools/runner-kubernetes-infra
