.integration kubernetes:
  extends:
    - .rules:merge_request_pipelines:no_docs
  tags:
    - kubernetes_integration
  stage: test kubernetes integration
  resource_group: $CI_COMMIT_BRANCH
  needs:
    - 'provision integration kubernetes'
  variables:
    KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: "k8s-runner-integration-tests-runner-$CI_PIPELINE_ID"
  before_script:
    - go install gotest.tools/gotestsum@latest
  artifacts:
    when: always
    paths:
      - junit_report.xml
    reports:
      junit: junit_report.xml

provision integration kubernetes:
  extends:
  - .integration kubernetes
  needs:
  - 'prepare done'
  variables:
    KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: "k8s-runner-integration-tests-provisioner"
  script:
  - mage k8s:provisionIntegrationKubernetes $CI_PIPELINE_ID

integration kubernetes exec legacy:
  extends:
  - .integration kubernetes
  variables:
    CI_RUNNER_TEST_FEATURE_FLAG: "FF_USE_LEGACY_KUBERNETES_EXECUTION_STRATEGY"
    CI_RUNNER_TEST_FEATURE_FLAG_VALUE: "true"
  script:
  - >
    gotestsum --format=pkgname-and-test-fails --format-hide-empty-pkg --rerun-fails=3 \
      --hide-summary output --packages=gitlab.com/gitlab-org/gitlab-runner/executors/kubernetes \
      --junitfile=junit_report.xml --junitfile-hide-empty-pkg -- \
      -timeout=10m -parallel=20 -run=TestRunIntegrationTestsWithFeatureFlag \
      -tags=integration,kubernetes ./executors/kubernetes/...

integration kubernetes attach:
  extends:
    - .integration kubernetes
  variables:
    CI_RUNNER_TEST_FEATURE_FLAG: "FF_USE_LEGACY_KUBERNETES_EXECUTION_STRATEGY"
    CI_RUNNER_TEST_FEATURE_FLAG_VALUE: "false"
  script:
    - >
      gotestsum --format=pkgname-and-test-fails --format-hide-empty-pkg --rerun-fails=3 \
        --hide-summary output --packages=gitlab.com/gitlab-org/gitlab-runner/executors/kubernetes \
        --hide-summary output--junitfile=junit_report.xml --junitfile-hide-empty-pkg -- \
        -timeout=10m -parallel=20 -run=TestRunIntegrationTestsWithFeatureFlag \
        -tags=integration,kubernetes ./executors/kubernetes/...

integration kubernetes:
  extends:
    - .integration kubernetes
  script:
    - >
      gotestsum --format=pkgname-and-test-fails --format-hide-empty-pkg --rerun-fails=3 \
        --hide-summary output --packages=gitlab.com/gitlab-org/gitlab-runner/executors/kubernetes \
        --junitfile=junit_report.xml --junitfile-hide-empty-pkg -- \
        -timeout=10m -parallel=20 -skip=TestRunIntegrationTestsWithFeatureFlag \
        -tags=integration,kubernetes ./executors/kubernetes/...

destroy integration kubernetes:
  extends:
  - .integration kubernetes
  needs:
  - job: 'integration kubernetes'
    optional: true
  - job: 'integration kubernetes exec legacy'
    optional: true
  - job: 'integration kubernetes attach'
    optional: true
  variables:
    KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: "k8s-runner-integration-tests-provisioner"
  script:
  - mage k8s:destroyIntegrationKubernetes $CI_PIPELINE_ID
